name: Deploy

on:
  push:
    branches:
      - main

env:
  VITE_SUPABASE_TOKEN: ${{ secrets.VITE_SUPABASE_TOKEN }}
  VITE_SUPABASE_PROJECT: ${{ secrets.VITE_SUPABASE_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          preCommands: npm run build
          command: pages deploy dist --project-name buku-dongeng
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}